name: alephants
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9207626229617745
title: Creative Happy Performers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76161586-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191c2a'
    - '#004934'
    - '#c9c3b1'
    - '#5f706e'
    - '#68b06a'
  brandStrength: 0.3125
  lightness: 0.5606644796207547
  saturation: 0.7029854925349355
  rhythmicContrast: 0.7468362285289913
purpose: []
